# Use the latest LTS version of Node.js
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Accept build-time arg for the React app base URL and export it as env
# ARG REACT_APP_BASE_URL
# ENV REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Accept the same build arg in the final stage
ARG REACT_APP_BASE_URL
# Set it as an environment variable in the final image
ENV REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

# Copy the rest of your application files
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
