stages:
  - build

build_job:
  stage: build
  script:
    - echo "Pipeline started from GitHub!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "trigger" # <--- Required for the API call
