services:
  backend:
    # If you want to build the backend from source, uncomment the build line
    build: ./backend

    # If you want to use a pre-built image, uncomment the image line
    # image: sophin/fileshare-backend:latest
    container_name: fileshare_backend
    ports:
      - "2000:2000"
    # Uncomment volumes if you want live reload during development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - file-share-backend:/app/uploads
    env_file: .env
    environment:
      # MYSQL_HOST: ${MYSQL_HOST}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DB: ${MYSQL_DATABASE}
      NODE_ENV: production
      MAX_FILE_SIZE: 20971520
    depends_on:
      mysql:
        condition: service_healthy # Wait until MySQL is healthy

  mysql:
    image: mysql:8.0
    # Reason we explicitly set the .env file is to ensure that it uses the env variables defined in the .env file. Sometime
    env_file: .env
    container_name: fileshare_mysql
    ports:
      - "3306:3306"
    volumes:
      - file-share-mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      # Add healthcheck
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      # Make sure to use interval 10s because for some reason the default 5s is not enough for MySQL to be healthy as a result backend and nagios will not start
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    # If you want to build the frontend from source, uncomment the build line
    build: ./frontend

    # If you want to use a pre-built image, uncomment the image line
    # image: sophin/fileshare-frontend:latest

    container_name: fileshare_frontend
    stdin_open: true
    tty: true
    # Uncomment volumes if you want live reload during development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  file-share-mysql:
  file-share-backend:
