services:
  backend:
    # If you want to build the backend from source, uncomment the build line
    # build: ./backend

    # If you want to use a pre-built image, uncomment the image line
    image: sophin/fileshare-backend:latest
    container_name: api_backend
    ports:
      - "2000:2000"
    # Uncomment volumes if you want live reload during development
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      NODE_ENV: production
      MAX_FILE_SIZE: 20971520
    depends_on:
      mysql:
        condition: service_healthy # Wait until MySQL is healthy
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.212

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - file-share-mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      # Add healthcheck
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.213
  client:
    # If you want to build the frontend from source, uncomment the build line
    # build: ./frontend

    # If you want to use a pre-built image, uncomment the image line
    image: sophin/fileshare-frontend:latest
    container_name: client_frontend
    stdin_open: true
    tty: true
    # Uncomment volumes if you want live reload during development
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.211

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - backend
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.210

volumes:
  file-share-mysql:
  file-share-backend:
networks:
  macvlan_net:
    external: true
# To create the macvlan network globally, run the following command:
# docker network create -d macvlan --subnet=192.168.0.0/24 --gateway=192.168.0.1 -o parent=eth0 macvlan_net

# networks:
#   macvlan_net:
#     driver: macvlan
#     driver_opts:
#       parent: eth0  # ← replace with your actual Wi-Fi interface (like wlp2s0)
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24
#           gateway: 192.168.0.1
