server {
    client_max_body_size 3G;
    listen 80;
    server_name localhost;

    # Handle API requests
    location /api/ {
        proxy_pass http://fileshare_backend:2000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Handle all other requests - serve React app from frontend container
    location / {
        proxy_pass http://fileshare_frontend:2000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}